### ISSUE TITLE
confused about current usability

### ISSUE THREAD

**Issue by greywood** [lahwaacz/arch-wiki-docs#30] opened 2022-08-30 04:01 UTC
Hello,

Thank-you for the free software!

However, I am having some problems using it. First, I was having issues with the unmaintained package for simplemediawiki, although it was installed via pip3 I still had to the 2to3 command against it to get it more compliant with python 3 (it still uses 'print' without brackets and imports old packages, for example)

Once I got that seemingly working I tried to run arch-wiki-docs again and I am still receiving errors, the latest which is:

```
./arch-wiki-docs.py --output-directory /tmp/
Downloading CSS...
  ArchWikiOffline.css
Traceback (most recent call last):
  File "./arch-wiki-docs.py", line 39, in <module>
    aw.print_namespaces()
  File "/home/username/scripts/arch-wiki-docs/ArchWiki/ArchWiki.py", line 152, in print_namespaces
    nsmap = self.namespaces()
  File "/home/username/scripts/arch-wiki-docs/ArchWiki/ArchWiki.py", line 147, in namespaces
    self._namespaces = super().namespaces()
  File "/home/username/.local/lib/python3.7/site-packages/simplemediawiki.py", line 271, in namespaces
    'siprop': 'namespaces'})
  File "/home/username/.local/lib/python3.7/site-packages/simplemediawiki.py", line 149, in call
    return json.loads(self._fetch_http(self._api_url, params))
  File "/home/username/.local/lib/python3.7/site-packages/simplemediawiki.py", line 124, in _fetch_http
    response = self._opener.open(request)
  File "/usr/lib/python3.7/urllib/request.py", line 523, in open
    req = meth(req)
  File "/usr/lib/python3.7/urllib/request.py", line 1254, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.
```

So I guess my question is: **Is arch-wiki-docs currently in a working state?** I just want to know before I try to fix more issues just to see another one pop up.

Thanks!

**Comment by lahwaacz** [comment] 2022-08-30 05:43
[python-simplemediawiki](https://github.com/iliana/python-simplemediawiki) should work fine with Python 3. I'm not getting this error with Python 3.10.6-1.

**Comment by lahwaacz** [comment] 2022-11-15 19:11
Closing as I can't reproduce.

**Closed by lahwaacz** 2022-11-15 19:11 UTC
Labels: invalid
